# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-19 13:32
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='finish_date',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='competition',
            name='start_date',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
