# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-20 11:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0002_auto_20151219_1332'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='type',
            field=models.CharField(choices=[(1, 'Text'), (2, 'Image'), (3, 'Video')], default=1, max_length=2),
        ),
    ]
