# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-20 11:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0003_competition_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='type',
            field=models.CharField(choices=[('txt', 'Text'), ('img', 'Image'), ('vid', 'Video')], default='txt', max_length=5),
        ),
    ]
