# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-20 13:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0004_auto_20151220_1156'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='image_url',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='entry',
            name='text',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='entry',
            name='video_url',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
