# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-21 11:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0003_auto_20151221_1135'),
        ('competitions', '0006_entry_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='text',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='title',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='video_url',
        ),
        migrations.AddField(
            model_name='entry',
            name='feed',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='feeds.Feed'),
        ),
    ]
