# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-22 12:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0007_auto_20151221_1135'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='competition',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='feed',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='user',
        ),
        migrations.DeleteModel(
            name='Entry',
        ),
    ]
