# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-27 01:45
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0008_auto_20151222_1246'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='finish_upload_date',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
