# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-14 04:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0011_competition_result_declaration_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='status',
            field=models.CharField(choices=[(b'n', b'not calculated'), (b'y', b'calculated')], default=b'n', max_length=1),
        ),
    ]
