# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-20 16:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='competitions_entry',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
