# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-21 11:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0002_auto_20151218_2225'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='video_url',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='feed',
            name='image_url',
            field=models.TextField(max_length=500, null=True),
        ),
    ]
