# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-09 07:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0005_auto_20160127_0145'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='judge_points',
            field=models.IntegerField(default=0),
        ),
    ]
