# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-14 04:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0007_feed_share_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='audience_points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='feed',
            name='total_points',
            field=models.IntegerField(default=0),
        ),
    ]
